version: '3.8'

services:
  server: #hostname
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: c-server
    networks:
      - c-network

  client: #hostname
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: c-client
    networks:
      - c-network
    depends_on:
      - server  # Ensure the server container starts before the client

networks:
  c-network:
    driver: bridge
